name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking and build
        run: npm run build
        env:
          PUBLIC_GCAL_ID: ${{ secrets.PUBLIC_GCAL_ID || '' }}
          PUBLIC_GCAL_TZ: ${{ secrets.PUBLIC_GCAL_TZ || 'Asia/Tokyo' }}
          PUBLIC_GCAL_PARAMS: ${{ secrets.PUBLIC_GCAL_PARAMS || '' }}

      - name: Deploy to Firebase Hosting (Preview)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COR_JP_WEB }}
          projectId: cor-jp-web
          expires: 30d

      - name: Deploy to Firebase Hosting (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COR_JP_WEB }}
          projectId: cor-jp-web
          channelId: live